import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { getServerSession } from "@/features/auth/services/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession()
  const basePath = process.env.NEXTAUTH_BASE_PATH

  return (
    <html lang="es">
      <body className={`${inter.className} bg-tremor-background-muted text-tremor-content-strong dark:bg-dark-tremor-background dark:text-dark-tremor-content-strong flex h-screen flex-col`}>
        <Providers session={session} basePath={basePath}>{children}</Providers>
      </body>
    </html>
  );
}